name: build-release-binary

run-name: Create Github Release for GoLang binary

on: 
  push:
    tags:
    - 'v*'

env:
  binary-name: snakesneaks
  output-dir: bin/
jobs:
  build-and-release:
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    steps:
    - name: Checkout Source
      uses: actions/checkout@v4

    - name: setup Go Lang
      uses: actions/setup-go@v3
      with:
        go-version: '^1.19.2'
        
    - name: Go Build
      run: |
        make x-build

    - name: release
      uses: softprops/action-gh-release@v1
      with:
        name: Release ${{ github.ref }}
        tag_name: ${{ github.ref }}
        generate_release_notes: true
        files: |
          bin/goxz
